# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARM-HUB-WE-01-SC'
    subscriptionId: 'f53eaef3-9a1e-4bcb-afd2-7afc73c058ff'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARM-HUB-01'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/chandiryn/hub-and-spoke-playground/blob/main/hub-01-bicep/hub-01.bicep'
    overrideParameters: 'ARM-HUB-01'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

